### ISSUE TITLE
backend crashes on deactivating plugin

### ISSUE THREAD

**Issue by daniyals14** [valu-digital/wp-graphql-polylang#13]
We're running a WordPress multisite installation and when the 'WP GraphQL' plugin is deactivated, it crashes the backend and generates the following log

[Thu Jan 02 13:22:40.765263 2020] [php7:notice] [pid 3656] [client 172.31.15.44:50646] PHP Fatal error:  Uncaught Error: Class ‘WPGraphQL\\Router’ not found in /var/www/html/xyz/wp-content/plugins/wp-graphql-polylang-0.3.5/src/Loader.php:110\nStack trace:\n#0 /var/www/html/xyz/wp-content/plugins/wp-graphql-polylang-0.3.5/src/Loader.php(47): WPGraphQL\\Extensions\\Polylang\\Loader->is_graphql_request()\n#1 /var/www/html/xyz/wp-includes/class-wp-hook.php(288): WPGraphQL\\Extensions\\Polylang\\Loader->get_pll_model(‘PLL_Model’)\n#2 /var/www/html/xyz/wp-includes/plugin.php(206): WP_Hook->apply_filters(‘PLL_Model’, Array)\n#3 /var/www/html/xyz/wp-content/plugins/polylang/include/class-polylang.php(222): apply_filters(‘pll_model’, ‘PLL_Model’)\n#4 /var/www/html/xyz/wp-includes/class-wp-hook.php(288): Polylang->init(‘’)\n#5 /var/www/html/xyz/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)\n#6 /var/www/html/xyz/wp-includes/plugin.php(478): WP_Hook->do_action(Array)\n#7 /var/www/html/xyz/wp-settings.php(392): do_action(’plugins_loade in /var/www/html/xyz/wp-content/plugins/wp-graphql-polylang-0.3.5/src/Loader.php on line 110, referer: https://www.xyz.com/xyz/wp-admin/edit.php?s=indian&post_status=all&post_type=post&action=-1&m=0&cat=0&seo_filter&readability_filter&paged=1&action2=-1

**Comment by esamattis** [comment]
Fixed in v0.3.7
