### ISSUE TITLE
Menu-Language not working

### ISSUE THREAD

**Issue by davidfaber** [valu-digital/wp-graphql-polylang#28]
Hi there,
First of all, wp-graphql-polylang is awesome!

I found an issue when using it with WPGraphql Version 0.12.3 where menu-languages are not working anymore.

I figured out, that the filter graphql_menu_item_connection_args you're using has been removed and is not applied anymore.

Maybe there is another way, but I couldn't find one.

Thanks in advance,
David

**Comment by davidfaber** [comment]
So... I did find a way... which is more like a hack and not perfect at all. But it works and might be a good start for you guys!

Hope this helps!

**Comment by esamattis** [comment]
Let's figure out why `graphql_menu_item_connection_args` was removed...

**Comment by esamattis** [comment]
Fixed by https://github.com/valu-digital/wp-graphql-polylang/pull/29

**Comment by esamattis** [comment]
Fixed in v0.5.0 
https://github.com/valu-digital/wp-graphql-polylang/compare/v0.4.0...v0.5.0

**Comment by baoc75** [comment]
Can anyone confirm if it is not working in the lastest version?
