### ISSUE TITLE
Neither `menu` nor `menuItem` has field "language"

### ISSUE THREAD

**Issue by SilencerWeb** [valu-digital/wp-graphql-polylang#33]
Neither `menu` nor `menuItem` has field "language"

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/20713191/95072007-fcb67d80-0723-11eb-8a9a-0c6e35ed26fd.png)
![image](https://user-images.githubusercontent.com/20713191/95071991-f4f6d900-0723-11eb-9ab7-5f765cd7c024.png)
</details>

WordPress v5.5.1
Polylang v2.8.2
WP GraphQL Polylang v0.5.0
WP GraphQL v0.13.1
WP GraphiQL v1.0.1

**Comment by esamattis** [comment]
You don't translate the menus or menu items themselves. Instead Polylang automatically generates localised versions of the menu locations you have created with `register_nav_menus()` and you are supposed create different menus for each language and assign them to the corresponding locations.

Using the `location` and `language` where args it is possible to query menu items by the language:


```graphql
{
    # Get translated version of a given menu
    menuItems(where: { language: EN, location: FOOTER_MENU }) {
        nodes {
            label
            url
        }
    }
}
```

**Comment by SilencerWeb** [comment]
@esamattis what's the problem to add the field "language" if we even have a filter for this? This information is very useful

**Comment by esamattis** [comment]
From where would you get the language for it?

One menu can be assigned to a multiple locations so every menu and menu item can have multiple languages in a sense.

Just try this query

```graphql
{
  menus {
    nodes {
      name
      locations
    }
  }
}
```

and you see that the `locations` field is an array.

**Comment by SilencerWeb** [comment]
I see, it is pretty complicated.

So as I understand we can't add the field `language` either to `menu` or `menuItem`, am I right?

**Comment by esamattis** [comment]
Yup. That's just how Polylang works and there's really nothing we can do here. If you want them to be translatable you need to bring it up with the Polylang folks.

**Comment by esamattis** [comment]
Btw, you might want to read this comment if you want to better understand how the menus work in Polylang:

https://github.com/valu-digital/wp-graphql-polylang/issues/25#issuecomment-705703786

**Comment by SilencerWeb** [comment]
Yup, I've read it already, thanks a lot for such a detailed explanation :)

**Comment by esamattis** [comment]
Oh and just in case if you didn't notice. You can use the `connectedNode` field on a menu item to get node the menu item points to and if it a post type that is translated you can get the language of it of course. 

Example:

```graphql
{
  menuItems(where: {location: FOOTER_MENU, language: EN}) {
    nodes {
      label
      url
      connectedNode {
        node {
          ... on Page {
            title
            language {
              name
            }
          }
        }
      }
    }
  }
}
```
