### ISSUE TITLE
The plugin does not show "language" for WooCommerce products

### ISSUE THREAD

**Issue by MobyDigg** [valu-digital/wp-graphql-polylang#34]
I am using wp-graphql-polylang and wp-graphql-woocommerce, but when querying products I cannot find the "language" schema. I now used a work around through an ACF select field, but it would be nice to have languages available for WooCommerce products 👍

**Comment by esamattis** [comment]
There's no WooCommerence support in this plugin and I don't think it even would belong to this plugin since WooCommerence support for Polylang is shipped in a seperate plugin:

<https://polylang.pro/downloads/polylang-for-woocommerce/>

I'd prefer seeing `wp-graphql-polylang-woocommerce` that would implement it.

That being said we don't have any plans to create one at the moment but would happily to link to one if somebody would create it.

**Comment by brianpereradap** [comment]
> I am using wp-graphql-polylang and wp-graphql-woocommerce, but when querying products I cannot find the "language" schema. I now used a work around through an ACF select field, but it would be nice to have languages available for WooCommerce products 👍

@MobyDigg can you share the details about the approach you took using "ACF select field"?

**Comment by proka89** [comment]
> > I am using wp-graphql-polylang and wp-graphql-woocommerce, but when querying products I cannot find the "language" schema. I now used a work around through an ACF select field, but it would be nice to have languages available for WooCommerce products 👍
> 
> @MobyDigg can you share the details about the approach you took using "ACF select field"?

You can do something like this:

```php
add_action(
	'graphql_register_types',
	function() {
		register_graphql_field(
			'Product',
			'language',
			array(
				'type'        => 'String',
				'description' => __( 'Product Language', 'wp-graphql' ),
				'resolve'     => function( $post ) {
					return pll_get_post_language( $post->ID );
				},
			)
		);
	}
);

add_action(
	'graphql_register_types',
	function() {
		register_graphql_field(
			'Product',
			'translations',
			array(
				'type'        => array(
					'list_of' => 'Product',
				),
				'description' => __( 'Product Translations', 'wp-graphql' ),
				'resolve'     => function ( \WPGraphQL\WooCommerce\Model\Product $post ) {
					$posts = array();

					if ( $post->isPreview ) {
						$parent       = wp_get_post_parent_id( $post->ID );
						$translations = pll_get_post_translations( $parent );
					} else {
						$translations = pll_get_post_translations( $post->ID );
					}

					foreach ( $translations as $lang => $post_id ) {
						$translation = \WP_Post::get_instance( $post_id );

						if ( ! $translation ) {
							continue;
						}

						if ( is_wp_error( $translation ) ) {
							continue;
						}

						if ( $post->ID === $translation->ID ) {
							continue;
						}

						if ( $post->isPreview && $parent === $translation->ID ) {
							continue;
						}

						$model = new \WPGraphQL\WooCommerce\Model\Product( $translation );

						if ( $model->is_private() ) {
							continue;
						}

						$posts[] = $model;
					}

					return $posts;
				},
			)
		);
	}
);

add_action(
	'graphql_register_types',
	function () {
		register_graphql_field(
			'RootQueryToProductConnectionWhereArgs',
			'language',
			array(
				'type'        => 'String',
				'description' => __( 'The Language of the post object to filter by' ),
			)
		);
	}
);

add_filter(
	'graphql_product_connection_query_args',
	function ( $query_args, $source, $args, $context, $info ) {
		$language = $args['where']['language'];

		if ( isset( $language ) ) {
			$query_args = array(
				'lang' => $language,
			);
		}

		return $query_args;
	},
	10,
	5
);```

With this you will be able to use translations, languages.... and everything else for the products. Just add it to the functions.php.
