### ISSUE TITLE
How to get actual language for product [polylang/woocomerce]

### ISSUE THREAD

**Issue by MrHDOLEK** [valu-digital/wp-graphql-polylang#36]
Hi 
I have a problem with a get a real language for products.
How can you download the current language of the product or is it possible?.Thanks for the help in advance
`  "data": {
    "products": {
      "nodes": [
        {
          "language": {
            "code": "PL"
          },
          "name": "test",
          "slug": "91"
        },
        {
          "language": {
            "code": "PL" ` **<---- here it should be EN**`
          },
          "name": "English prod",
          "slug": "test-prod"
        },`

**Comment by esamattis** [comment]
Unfortunately there's no Woocommerence support in this plugin. See https://github.com/valu-digital/wp-graphql-polylang/issues/34#issuecomment-712224991
