### ISSUE TITLE
IsFrontPage and isPostsPage

### ISSUE THREAD

**Issue by luisbraga** [valu-digital/wp-graphql-polylang#38]
Hi,

While working on a recent project I realised that both this fields don't return the values I would expect for translated posts.
I've ended up overriding the original resolvers to achieve this.
Let me know if you see fit and I'd be happy to open a PR.

```php
add_filter( 'graphql_Page_fields', function( $fields ) {
  if ( isset( $fields['isFrontPage'] ) ) {
    $fields['isFrontPage']['resolve'] = function(\WPGraphQL\Model\Post $post) {
      if ( 'page' !== $post->post_type || 'page' !== get_option( 'show_on_front' ) ) {
        return false;
      }

      $post_translations = array_values(pll_get_post_translations($post->ID));
      $front_page_id     = absint( get_option( 'page_on_front', 0 ) );

      return in_array($front_page_id, $post_translations);
    };
  }

  if ( isset( $fields['isPostsPage'] ) ) {
    $fields['isPostsPage']['resolve'] = function(\WPGraphQL\Model\Post $post) {
      if ( 'page' !== $post->post_type ) {
        return false;
      }

      $post_translations = array_values(pll_get_post_translations($post->ID));
      $page_for_posts_id = absint( get_option( 'page_for_posts', 0 ) );

      return 'posts' !== get_option( 'show_on_front', 'posts' ) && in_array($page_for_posts_id, $post_translations) === true;
    };
  }
  return $fields;
}, 10, 1 );
```

**Comment by esamattis** [comment]
Interesting idea to replace the resolvers all together! A PR is welcome for sure.

But I think we need more robust condition than just `if ( isset( $fields['isPostsPage'] ) )` because this will match any graphql type with field named `isPostsPage`. Can we add an additional condition for the type too?

**Comment by luisbraga** [comment]
This filter will only take effect on the Page type: `graphql_Page_fields`.  
Could you elaborate? Maybe I'm missing something?

**Comment by esamattis** [comment]
Fixed in https://github.com/valu-digital/wp-graphql-polylang/pull/48
