### ISSUE TITLE
language filter is not working for woocommerce products

### ISSUE THREAD

**Issue by vstrelianyi** [valu-digital/wp-graphql-polylang#49]
No language field in where:{ } parameter when querying woocommerce products

**Comment by sslnyx** [comment]
query MyQuery {
  productCategories(where: {language: ZH}) {
    edges {
      node {
        id
        name
        products {
          nodes {
            name
            id
          }
        }
      }
    }
  }
}

I can get the language by "productCategories", then get the products from the category.

**Comment by vstrelianyi** [comment]
Hm.. it seems that there is no language in the schema
![image](https://user-images.githubusercontent.com/15492290/133441310-751a1e7e-3535-4906-8e7f-d93125a44fc6.png)
, so I'm getting an error
![image](https://user-images.githubusercontent.com/15492290/133441245-b71c3257-0aa8-45bf-8bee-1372929a6514.png)

**Comment by sslnyx** [comment]
![productquery](https://user-images.githubusercontent.com/33405884/133667131-b5d744c3-804e-427b-9595-61bc057f122a.JPG)

Just fresh install a demo project. I have it with the latest version 0.5.0 of this plugin.

https://github.com/valu-digital/wp-graphql-polylang/releases

**Comment by vstrelianyi** [comment]
ok, I have found the issue
I needed to check the Product categories box in Polylang settings
![image](https://user-images.githubusercontent.com/15492290/133753140-1f2e5eb0-c955-4f63-8a5c-26d40b6da5c9.png)

**Comment by vstrelianyi** [comment]
@sslnyx  thx for your time
the issue is closed, I hope our dialog will be useful for others who might face  it..  )
