### ISSUE TITLE
Add docs to README for running tests locally

### ISSUE THREAD

**Issue by jasonbahl** [valu-digital/wp-graphql-polylang#7]
In trying to help fix an issue I attempted to install the plugin and run tests locally. 

I got close, but missed some detail and was unable to run the tests locally to help debug an issue. 

It would be good to have a step-by-step outline in the README of how to get tests running locally. 

Thanks!

**Comment by epeli** [comment]
Here https://github.com/valu-digital/wp-graphql-polylang/blob/master/CONTRIBUTING.md
